pytutor/pytutor/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles import views


from django.contrib import admin
admin.autodiscover()

from django.contrib.auth import views as auth_views

from social.views import SocialView


urlpatterns = patterns('',

    #BASE URL MAPPINGS
    url(r'^$', 'pytutor.views.home'),
    url(r'^admin/', include(admin.site.urls)),

    # User URL MAPPINGS
    url(r'^study/report$', 'tutor.student_views.report'),
    url(r'^study/report/(?P<user_name>.*)[/]$', 'tutor.student_views.report'),
    url(r'^study/question_detail/([0-9]+?)[/]$', 'tutor.student_views.question_detail'),
    #no idea ^

    # TUTOR URL MAPPINGS
    # --------------------------------- STUDYING
    url(r'^tutor$', 'tutor.study_views.study'),
    url(r'^tutor/(?P<sticky_id>[0-9]+?)[/]$', 'tutor.study_views.study'),
    url(r'^tutor/tag/(?P<study_tag>.*)[/]$', 'tutor.study_views.study'),
    # url(r'^tutor/(?P<sticky_id>[0-9]+?)/tag/(?P<study_tag>.*)[/]$', 'tutor.study_views.study'),
    url(r'^tutor/(?P<pk>[0-9]+?)/respond[/]$', 'tutor.study_views.study'),
    url(r'^tutor/([0-9]+?)/solutions[/]$', 'tutor.study_views.solutions'),
    url(r'^tutor/tags', 'tutor.study_views.tags'),
    # url(r'^tutor/no_questions$', 'tutor.study_views.no_questions'),
    url(r'^tutor/response/submit', 'tutor.study_views.respond'),

    # --------------------------------- EDITING
    url(r'^question/list/(?P<editor_name>.*)[/]$', 'tutor.editor_views.list'),
    url(r'^question/list[/]$', 'tutor.editor_views.list'),
    url(r'^question/(?P<pk>[0-9]+?)/dup[/]$', 'tutor.editor_views.dup'),
    url(r'^question/new', 'tutor.editor_views.question_form'),
    url(r'^question/(?P<pk>[0-9]+?)/edit[/]$', 'tutor.editor_views.question_form'),
    url(r'^question/(?P<pk>[0-9]+?)/delete[/]$', 'tutor.editor_views.delete_question'),
    url(r'^question/save', 'tutor.editor_views.save_question'),
    url(r'^question/(?P<pk>[0-9]+?)/diff/(?P<v1>[0-9]+?),(?P<v2>[0-9]+?)[/]$', 'tutor.editor_views.diff'),
    url(r'^question/(\d+)/revert/(\d+)[/]$', 'tutor.editor_views.revert'),
    url(r'^question/test/save', 'tutor.editor_views.add_test'),
    url(r'^question/test/(?P<pk>[0-9]+?)/del', 'tutor.editor_views.del_test'),


    # --------------------------------- USERS
    url(r'^change_pass[/]', 'tutor.user_views.change_pass'),
    url(r'^login$', 'tutor.user_views.user_login'),
    url(r'^logout$', 'tutor.user_views.user_logout'),
    url(r'^login-sorry$', 'tutor.user_views.login_error'),
    url(r'^register$', 'tutor.user_views.register'),


    # --------------------------------- USER PROFILE
    url(r'^~(.*)[/]$', 'social.views.public'),
    url(r'^profile[/]$', 'social.views.profile'),
    url(r'^api/profile[/]$', SocialView.as_view()),
    url(r'^api/friend/find[/]$', 'social.views.find_friends'),
    url(r'^api/profile/pic[/]$', 'social.views.post_profile_pic'),
    url(r'^api/friendship/add[/]$', 'social.views.add_friend_request'),
    url(r'^api/friendship/accept[/]$', 'social.views.accept_friendship'),
    url(r'^api/social/status[/]$', 'social.views.social_status'),
)

# serve the user uploaded content as static media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pytutor/tutor/models.py
# tutor.models.py
# by: mxc
"""
Define the Django models for the
PyTutor application. Defines
key objects: Question.
"""

import json

from django.db import models
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from tutor.templatetags.tutor_extras import syn
from django.contrib.humanize.templatetags import humanize
from django.db import connection

class AbstractQuestion(models.Model):
    """A Question is a coding challenge for the studier.
    It provides them with a prompt and the name of the
    function they must write to solve the problem. Questions
    have a difficulty level and an arbitrary set of Tags
    that categorize them. Questions are meant to be edited
    wiki-style -- wtih many editors boldly making changes, but
    with a clear revision history and easy system for rolling them
    back."""

    levels = ["Basics: simple function, variables, operators (e.g., +,-,*/)",
        "Conditional statements, built-in functions",
        "Strings, basics",
        "Lists and loops",
        "Dictionaries, tuples, sets; string functions",
        "Multi-step problems, libraries, OOP, etc",
        "Hard problems"]

    level_choices = [(i,"{}. {}".format(i,x)) for i,x in enumerate(levels, start=1)]

    function_name = models.CharField(max_length=300)
    prompt = models.TextField()
    solution = models.TextField(blank=True)
    level = models.IntegerField(choices=level_choices, default=1)
    tags = models.CharField(max_length=500, blank=True)
    version = models.IntegerField(default=0)
    comment = models.CharField(max_length=500, blank=True)
    modified = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, related_name="%(app_label)s_%(class)s_creator")
    modifier = models.ForeignKey(User, related_name="%(app_label)s_%(class)s_modifer")

    def solution_pp(self):
        return syn(self.solution)

    def run_tests(self, code=""):
        tests = Test.objects.all().filter(question=self)
        if len(tests) == 0:
            return (False, [])

        if code == "":
            code = self.solution

        results = []
        passed = True


        for test, fail, result in [t.evaluate(code) for t in tests]:
            passed = passed and fail is None
            results.append((test, fail, result))

        return (passed, results)

    def level_label(self):
        return AbstractQuestion.levels[self.level - 1]


    class Meta:
        abstract = True
        ordering = ['-modified']

class QuestionManager(models.Manager):
    def by_level(self):
        questions = Question.objects.all()
        level_questions= {}
        for q in questions:
            level = level_questions.get(q.level, [])
            level.append(q)
        return level_questions

class Question(AbstractQuestion):

    FAILED = 1
    ACTIVE = 2
    DELETED = 3
    status_labels = ["","Failed", "Active", "Deleted"]
    status_css_classes = ["","danger", "success", "default"]
    status = models.IntegerField(default=FAILED)
    objects = QuestionManager()

    def as_json(self, wrap="", extra={}):
        q_data = {k: self.__dict__[k] for k in ('version', 'id', 'status')}
        q_data["creator"] = self.creator.username
        q_data["modifier"] = self.modifier.username
        q_data["created"] = humanize.naturaltime(self.created)
        q_data["modified"] = humanize.naturaltime(self.modified)
        q_data["status_label"] = self.status_labels[self.status]
        q_data["status_css"] = self.status_css_classes[self.status]

        for k,v in extra.items():
            q_data[k] = v

        if(len(wrap) > 0):
            return json.dumps({wrap: q_data})
        return json.dumps(q_data)


    def test_and_update(self, t=None):
        if self.status == Question.DELETED:
            return False

        if t is not None:
            test, ex, result = test.evaluate(user_function)
            passed = ex == None

        else:
            passed, results = self.run_tests()

        if self.status == Question.ACTIVE and not passed:
            self.status = Question.FAILED
            self.save()
            return True
        elif self.status == Question.FAILED and passed:
            self.status = Question.ACTIVE
            self.save()
            return True

        return False

    class Meta:
        unique_together = (('id', 'version'),)

class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ["function_name", "prompt", "solution", "level", "tags", "comment"]


class ArchiveQuestion(AbstractQuestion):
    """An ArchiveQuestion is created everytime a
    Question is updated. ArchiveQuestions can
    be reviewed and reverted to. For every Question
    there may be serveral ArchiveQuestions. Users
    Responses are linked to ArchiveQuestions, as
    are Flags. Comments are linked to the current
    Question, because, generally, comments will endure
    across vesions of a Question."""

    archived = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey(Question)

    def archive(self, q):

        self.function_name = q.function_name
        self.prompt = q.prompt
        self.solution = q.solution
        self.level = q.level
        self.tags = q.tags
        self.version = q.version
        self.comment = q.comment
        self.created = q.created
        self.creator = q.creator
        self.parent = q

    class Meta:
        unique_together = (('parent', 'version'),)


class Solution(ArchiveQuestion):
    """Solution objects provide custom comparators for ArchiveQuestions
which allows them to be hashed and ordered based on the code and version"""

    class Meta:
        proxy = True

    def test(self, tests):
        code = self.solution
        self.passed = True

        for test, fail, result in [t.evaluate(code) for t in tests]:
            self.passed = self.passed and fail is None

    def __ne__(self, other):
        return self.solution != other.solution

    def __eq__(self, other):
        return self.solution == other.solution

    def __hash__(self):
        return self.solution.__hash__()



class Test(models.Model):
    """
        Each Question must have at leat one Test
        before it can be published. Tests are meant
        to be dynamically executed by the system--
        each test has arguments to pass to the Users's
        function and the expected result. If all
        Question tests pass, the Response is considered correct.
    """
    args = models.CharField(blank=True, max_length=500)
    result = models.TextField()
    question = models.ForeignKey(Question)

    def evaluate(self, code=""):
        """Compile and execute the code in its own
           namespace, checking to see if the
           function returns the expected result
           when called with the given args.
           Returns a tuple of the return value
           and Exeception (or None)"""

        if code == "":
            code = Question.objects.get(pk=self.question.pk).solution

        ns = {}
        result = None
        fail = None

        try:
            # can get a syntax error here
            f = compile(code, '<string>', 'exec')
            # create the function in scope ns
            exec(f, ns)

            # create the string we're going to evaluate
            # might get a runtime error
            call = "result = {}({})".format(self.question.function_name, self.args)
            exec(call, ns)

            # if the result doesn't match the expected value
            # we'll get an assert error
            result = ns["result"]

            if not result == eval(self.result):
                msg = """
       Called: {}({})
     Expected: {}
Actual result: {}""".format(self.question.function_name, self.args, self.result, result)
                fail = AssertionError(msg)

        except Exception as ex:
            fail = ex

        return (self, fail, result)

    def to_code(self):
        str = 'assert {}({}) == {}'.format(self.question.function_name, self.args, self.result)
        return str


class TestForm(ModelForm):
    args = forms.CharField(required = False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    result = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Test
        fields = ["args", "result"]


def get_tag_info():
    cursor = connection.cursor()
    cursor.execute("SELECT distinct tags FROM tutor_question")
    tags = set()
    for row in cursor:
        q_tags = row[0].split(",")

        tags.update([t.lower().strip() for t in q_tags if len(t.strip()) > 0])

    tag_list = []

    sql = """
        select '{0}' as tag, avg(level) as avg_level, count(1) as question_count
            from tutor_question
                where
                    lower(tutor_question.tags) like '%{0}%'
            group by 1;
    """

    print(tags)

    for t in tags:
        try:
            s = sql.format(t,)
            cursor.execute(s)
            tag, level, count = cursor.fetchall()[0]
            tag_list.append({"tag": tag, "level": round(level, 1), "question_count": count})
        except Exception as e:
            print(s)
            raise e

    print(tag_list)

    return tag_list


class Response(models.Model):
    """A User's attempt to answer a Question
    is captured in the Response. The Response
    is evaluated against the Tests for a Question.
    If all tests are correctly passed, the Response
    is marked correct"""

    MAX_ATTEMPTS = 10

    code = models.TextField(blank=True, help_text="Your solution to this question.")
    is_correct = models.BooleanField(default=False)
    attempt = models.IntegerField(default=1)
    submitted = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question)

    def code_pp(self):
        return syn(self.code)

pytutor/pytutor/views.py
import random
import json
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib import messages
from django.db.models import Q

from tutor.models import *

def home(request):
    """Home Page Content...static for now."""

    
    questions = Question.objects.all()
    tags = []

    for question in questions:
        qtags = question.tags.split(",")
        qtags = [q.strip() for q in qtags]
        tags.extend(qtags)

    tags = set(tags)
    tags = sorted([t for t in tags])
    context = {"tags": tags}
    

    return render(request, 'home.html', context)

if  __name__ =='__main__':main()

pytutor/pytutor/templates/tutor/delete_confirm.html
<!-- Modal -->
<div id="del-confirm" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        Are you sure you want to delete this question?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <a href="/question/{{question.instance.id}}/delete" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>

pytutor/pytutor/templates/tutor/diff.html
{% extends "base.html" %}

{% block title %}PyTutor::Question Editor{% endblock %}

{% block body %}
<div class="panel panel-primary">
    <div class="panel-heading clearfix">
        <a href="/question/{{question.id}}/edit" title="back to the question editor"
           class="btn btn-warning pull-right">Go Back</a>

        <h2 class="panel-title">Compare revisions: <code>{{question.function_name}}</code></h2>
    </div>
    <div class="panel-body container-fluid">
        <div class="row pad-left pad-right">
        {% for v in versions %}
            <div class="well col-md-6 clearfix">
            {% if v.version == question.version %}
                <div class="btn btn-success pull-right">Current Version</div>
            {% else %}
                <a href="/question/{{question.id}}/revert/{{v.version}}" 
                   title="revert to this version" class="btn btn-danger pull-right">Revert</a>
            {% endif %}
                <dl class="dl-horizontal pull-left">
                    <dt>version:</dt><dd>{{v.version}}</dd>
                    <dt>modified:</dt><dd>{{v.modified}}</dd>
                    <dt>modifier:</dt><dd>{{v.modifier}}</dd>
                    <dt>comment:</dt><dd>{{v.comment}}</dd>
                </dl>
            </div>
        {% endfor %}
        </div>
        <h3 class="text-center">Function name</h3>
        {{titles|safe}}
        <h3 class="text-center">Question prompt</h3>
        {{prompts|safe}}
        <h3 class="text-center">Solution code</h3>
        {{solutions|safe}}
    </div>
</div>

{% endblock %}

pytutor/pytutor/templates/tutor/feedback.html
{% extends "base.html" %}

{% block title %}PyTutor Home{% endblock %}

{% block body %}

<section id="home">
	<h1>Question {{question.id}}</h1>
	<p>{{question.prompt}}</p>
    <!-- user response, evaluation/feedback, comments section, etc -->
</section>

{% endblock %}

pytutor/pytutor/templates/tutor/list.html
{% extends "base.html" %}

{% load humanize %}


{% block title %}PyTutor Home{% endblock %}

{% block body %}

<section id="question-list"class="panel panel-primary">
    <div class="panel-heading"><h2 class="panel-title">Question List: {{editor_name}}</h2></div>
    <div class="panel-body">
        <ul class="nav nav-pills" role="tablist">
          <li role="presentation" class="active"><a href="/question/list/{{user.username}}" title="questions I created or modified">My Questions</a></li>
          <li role="presentation"><a href="/question/list" title="all questions">All Questions</a></li>
        </ul>

        <table id="question-list" class="table table-striped table-bordered table-condensed table-sortable">
            <thead>
                <tr>
                  <th class="text-center">Function Name</th>
                  <th class="text-center">Status</th>
                  <th class="text-center">Created</th>
                  <th class="text-center">Creator</th>
                  <th class="text-center">Modified</th>
                  <th class="text-center">Last modifer</th>
                  <th class="text-center">Edits</th>
                  <th class="text-center">Level</th>
                  <th class="text-center">Tags</th>
                </tr>
            </thead>
            <tbody>
            {% for question in questions %}
                <tr>
                  <td data-sort-val="{{question.function_name}}">
                        <a href="/question/{{question.id}}/edit/"
                            title="edit this question"><strong><tt>{{question.function_name}}</tt></strong></a>
                        <div class="hidden"> <!-- will add to mouse over quick edit -->
                            <a href="/question/{{question.id}}/edit/" class="btn btn-primary btn-xs" title="edit this question">edit</a>
                            <a href="/question/{{question.id}}/dup/" class="btn btn-info btn-xs" title="duplicate this question">duplicate</a>
                            <a href="/question/{{question.id}}/delete/" class="btn btn-danger btn-xs"  title="delete to this question">delete</a>
                        </div>
                  </td>
                  <td data-sort-val="{{question.status_label}}">
                        {% if question.status  == 2 %}                           
                            <label class="label label-success center-block">Active</label>
                        {% elif question.status == 1 %}
                            <label class="label label-danger center-block">Failed</label>
                        {% else %}
                           <label class="label label-default disabled center-block">Disabled</label>
                        {% endif %}
                  </td>
                  
                  <td data-sort-val="{{question.created.timestamp}}">{{question.created|naturaltime}}</td>
                  <td class="text-center">
                        <a href="/question/list/{{question.creator}}/" title="questions created or modified by {{question.creator}}">{{question.creator}}</a><br>
                  </td>
                  <td data-sort-val="{{question.modified.timestamp}}">{{question.modified|naturaltime}}</td>
                  <td class="text-center">
                        <a href="/question/list/{{question.modifier}}/" title="questions created or modified by {{question.modifier}}">{{question.modifier}}</a><br>
                  </td>
                  <td class="text-center">{{question.version}}</td>
                  <td class="text-center">{{question.level}}</td>
                  <td>{{question.tags}}</td>
                </tr>
              {% endfor %}
            </tbody>
        </table>
    </div>
</section>

{% endblock %}

pytutor/pytutor/templates/tutor/no_questions.html
{% extends "base.html" %}

{% block title %}PyTutor{% endblock %}

{% block body %}

<section id="home">
    <h1>There are no questions yet!</h1>
	Why not <a href="new">create one</a> yourself?
</section>

{% endblock %}

pytutor/pytutor/templates/tutor/question_editor_tests.html
{% load humanize %}

<div id="question-info" class="well"></div>

<ul id="question-edit-tabs" class="nav nav-tabs" role="tablist">
  <li class="active"><a href="#tests" role="tab" data-toggle="tab">Test Cases</a></li>
  <li><a href="#history" role="tab" data-toggle="tab">View History</a></li>
</ul>

<div class="tab-content">
    <div class="tab-pane active panel panel-default" id="tests">
        <header class="panel-heading">
            <h2 class="panel-title">Tests</h2>
        </header>
        <div class="panel-body">
            <form id="test-form" class="" action="/question/test/save" method="post">
                {% csrf_token %}
                <input id="test_question_id" type="hidden" name="question_id" value="{{pk}}">
                <div class="form-group">
                    {{ test_form.args.label_tag }} 
                    {{ test_form.args }}
                    <p class="help-text">
                        Valid Python arguments for this function, 
                        e.g. <var>'hi'</var>, <var>2,8</var>, or <var>[10,-6,15]</var>
                    </p>
                </div>
                <div class="form-group">
                    {{ test_form.result.label_tag }} 
                    <textarea id="id_result" class="form-control" name="result"></textarea>
                    <p class="help-text">
                        The valid Python object the function should return.
                    </p>
                </div>
                <input type="submit" value="add test" class="btn btn-success">
            </form>
            <h4>Test Results</h4>
            <ul id="test-list" class="list-group">
                <li>foo</li>
            </ul>
        </div> <!-- /panel body -->
    </div> <!-- /panel & tab-pane -->
  
    <div class="tab-pane panel panel-default" id="history">
        <header class="panel-heading">
            <h2 class="panel-title">Revisions</h2>
        </header>
        <div class="panel-body">
            <table class="table table-striped table-sortable table-condensed">
                <thead>
                    <tr>
                        <th>version</th>
                        <th class="text-center">date modified</th>
                        <th class="text-center">modified by</th>
                    </tr>
                </thead>
                <tbody>
                {% for aq in history %}
                    <tr data-toggle="tooltip" data-placement="bottom" data-content="comment: {{aq.comment}}">
                        <td>{{aq.version}}</td>
                        <td class="text-center" data-sort-value="{{aq.modified.timestap}}">
                        {%if aq.version == question.instance.version %}
                            <abbr title="latest revisions">{{aq.modified|naturaltime}}</abbr>
                        {% else %}
                            <a href="/question/{{pk}}/diff/{{question.instance.version}},{{aq.version}}"
                               title="click to see diff with current version">{{aq.modified|naturaltime}}</a>
                        {% endif %}
                         </td>
                        <td class="text-center">{{aq.modifier}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div> <!-- /panel body -->
    </div> <!-- /panel -->
</div> <!-- /tab content -->


{% verbatim %}
<script id="test-result-tmpl" type="text/template">
    <li class="list-group-item list-group-item-{{css_status}} msg_levelclearfix">
        <button alt="Delete this test"  class="delete-test btn pull-right btn-xs btn-{{css_status}}"><span class="glyphicon glyphicon-minus-sign"></span></button>

        <h4 class="inline"><span class="label label-{{css_status}}">{{status}}</span></h4>
        <tt>{{code}}</tt>
        {% if(!passed){ %}
            <pre>{{ error_msg }}</pre>
        {% } %}
    </li>
</script>



<script id="messages-tmpl" type="text/template">
    <div class="label label-{{msg_level}}">{{msg}}</div>
</script>


<script id="question-info-tmpl" type="text/template">
    <div id="status-msg"></div>
    <h4>
        Question Editor <small>(id. {{id}}, v. {{version}})</small>
        <span id="question-status-label" class="label label-{{status_css}}">{{status_label}}</span>
    </h4>
    <dl id="question-info" class="dl-horizontal">
        <dt>Created by:</dt>
        <dd><tt>{{creator}}</tt>, {{created}}</dd>
        <dt>Last modified by:</dt>
        <dd><tt>{{modifier}}</tt>, {{modified}}</dd>
    </dl>
</script>
{% endverbatim %}

<script>
var Question = Backbone.Model.extend();
var Message = Backbone.Model.extend();
var TestResult = Backbone.Model.extend();
var TestResults = Backbone.Collection.extend({
    model: TestResult,
});

var MessageView = Backbone.View.extend({
    
    template: _.template($('#messages-tmpl').html()),

    initialize: function() {
        this.listenTo(this.model, 'change', this.render);
    },
    
    render: function() {
        if(!this.model.get("msg").length)
            return this;
        
        this.$el.html(this.template(this.model.attributes));
        var _view = this;
        var clear = function() { _view.$el.html(''); }
        _.delay(clear, 5000);
        return this;
    }
});



var TestResultView = Backbone.View.extend({
    
    template: _.template($('#test-result-tmpl').html()),
    events: {
        "click .delete-test": "clear",
    },

    initialize: function() {
        this.listenTo(this.model, 'change', this.render);
        this.listenTo(this.model, 'destroy', this.remove);
    },
    
    render: function() {
      this.$el.html($(this.template(this.model.attributes)));
      return this;
    },

    clear: function() {
        var url = '/question/test/' + this.model.id + '/del';
        var _view = this;
        $.get( url ).success( function( response ) {
            question.set(JSON.parse(response.question_json));
            message.set(response.message);
            _view.remove();
        });
    },

});

var TestListView = Backbone.View.extend({
    
    initialize: function() {
        this.listenTo(TestResults, 'add', this.addTest);
        this.$el.html('');
    },

    addTest: function(test) {
        var trv = new TestResultView({model: test});
        this.$el.append(trv.render().el);
        return this;
    },
    
    render: function() {
        TestResults.each(this.addTest, this);
        return this;
    },

});

var QuestionInfoView = Backbone.View.extend({
    
    initialize: function() {
        this.listenTo(this.model, "change", this.render);
    },

    template: _.template($('#question-info-tmpl').html()),
    
    render: function() {
        var cx = this.model.attributes; 

        var html = this.template(cx);
        this.$el.html(html);
        var msgv = new MessageView({model: message, el: "#status-msg"});
        this.$el.append(msgv.render().el);

        // this is outside of our view template, but we still want to update it the old fashioned way
        $("#question-status-indicator").removeClass("label-warning").addClass("label-success");

        return this;
    }

});

var tests_data = {{tests_json|safe}};
var question_data = {{question_json|safe}};
var question = new Question(question_data);
var TestResults = new TestResults(tests_data);
var message = new Message({msg: '', msg_level: ''});

$("body").ready(function() {
    var dv = new QuestionInfoView({el: "#question-info", model: question});
    dv.render();

    var tlv = new TestListView({el: "#test-list"});
    tlv.render();
    
});


</script>

pytutor/pytutor/templates/tutor/question_form-part.html
<form id="question-form" class="" action="/question/save" method="post" role="form">
    {% csrf_token %}
    <input id="question_id" type="hidden" name="pk" value="{{pk}}">
    <input type="hidden" id="prompt" name="prompt">
    <input type="hidden" id="solution" name="solution">

    <div class="well nopad-top">
        <div id="question-tools" class="btn-group">
            <div class="btn-group">
                <a id="save-question" href="#save"
                    data-html="true"
                    data-toggle="tooltip" data-placement="bottom"
                    data-content="<kbd>{{os_ctrl}}-s</kbd> saves from the prompt and solution editors."
                    title="Save question"
                    class="btn btn-success btn-sm">
                    Save <span class="glyphicon glyphicon-record"></span>
                </a>
            </div>
            <div class="btn-group">
                <a id="run-tests" class="btn btn-primary btn-sm" href="#test">
                    Test <span class="glyphicon glyphicon-play-circle"></span>
                </a>
            </div>
            <div class="btn-group">
                <!-- Button trigger modal -->
                <a href="#del" type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#del-confirm">
                    Delete <span class="glyphicon glyphicon-remove-circle"></span>
                </a>
            </div>
        </div><!-- /submit buttons -->
        <div id="question-status-indicator" class="change-indicator pull-right label label-success margin-top"><span class="glyphicon glyphicon-flash"></span></div>

        <div class="form-group margin-top">
            <input id="id_function_name" 
               placeholder="Enter the name of the function the studier must create, e.g. is_prime" 
               class="form-control" type="text" value="{{question.instance.function_name}}" name="function_name" maxlength="300">
        </div>

         <div class="form-group row">
            <div class="col-md-1">{{ question.level.label_tag }}</div>
            <div class="col-md-11">{{ question.level }}</div>
        </div>

        <div class="form-group">
            {{ question.prompt.label_tag }}
            <div id="prompt-editor" class="code-editor" data-code-field="prompt">{{question.instance.prompt}}</div>
            <p class="help-block">Provide clear instructions and sample ouput where appropriate. This field accepts
                <a href="#mdhelp" class="tip"  data-keyboard="true"
                   title="showmarkdown cheatsheet" data-toggle="modal" 
                   data-target="#mdcheat">markdown</a></p>
        </div>
        <div class="form-group">
            {{ question.solution.label_tag }}
            <div id="solution-editor" class="code-editor" data-code-field="solution">{{question.instance.solution}}</div>
            <p class="help-block">Write your solution Python code here. It <em>must</em> pass all of the tetsts.</p>
        </div>
        <div class="form-group">
            <label for="id_tags">Tags:</label>
            <input id="id_tags" class="form-control" type="text" value="{{question.instance.tags}}" name="tags" maxlength="500">
        </div>
        <div class="form-group">
            {{ question.comment.label_tag }} 
            {{ question.comment }} 
        </div>
    </div>
</form>